# Generated by Django 6.1.2 on 2026-10-10 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat_app', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='user.appuser'),
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_app.room'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'datetime'], name='chat_app_me_room_id_9a796a_idx'),
        ),
    ]
